### ISSUE TITLE
Bad example of creds.py

### ISSUE THREAD

**Issue by aahnik** [alenpaul2001/Web-Screenshot-Bot#15]
Hi, its a bad practice to put secret tokens, directly into creds.py

In the code, you have smartly used, `os.getenv()`

But in the README, you have said people to put tokens directly in a code file.

I think a better option is using a `.env` file

example:

```
API_ID=089490
API_HASH=jfsij8u03...90sjsf
# others
```

You ( the developer and not the user ) just need to do three things:

1. `pip install python-dotenv`
2. Inside `creds.py`, 
```python
from dotenv import load_dotenv
load_dotenv()
```
3. Add `python-dotenv`, to `requirements.txt`

**Comment by alenpaulvarghese** [comment]
Editing creds.py is the easiest way if we are deploying manually,  I don't find the importance of introducing another file and dependence just to bear its overhead 🤷‍♂.

**Comment by aahnik** [comment]
Yup, I understand. At the end, this boils down to personal preferences. I appreciate your choice.
